In [2]:
# 2-1
import numpy as np

# 2-1번
x = np.array([[1,1,0.85,0.76],
              [1,1,0,0.24],
              [1,0,0.625,0.84],
              [1,0,0.45,0.96],
              [1,1,0.225,0.46],
              [1,0,0.25,0.7],
              [1,1,0.7,0.44],
              [1,0,0.3,0.4],
              [1,0,0.125,0.66]])

y = np.array([1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0])
w = np.array([0.0,0.0,0.0,0.0])
print("x:")
print(x)
print(x.shape)
print()

print("y:")
print(y)
print(y.shape)
print()

print("w:")
print(w)
print(w.shape)

x:
[[ 1.     1.     0.85   0.76 ]
 [ 1.     1.     0.    24.   ]
 [ 1.     0.     0.625  0.84 ]
 [ 1.     0.     0.45   0.96 ]
 [ 1.     1.     0.225  0.46 ]
 [ 1.     0.     0.25   0.7  ]
 [ 1.     1.     0.7    0.44 ]
 [ 1.     0.     0.3    0.4  ]
 [ 1.     0.     0.125  0.66 ]]
(9, 4)

y:
[1. 0. 1. 1. 0. 0. 1. 0. 1.]
(9,)

w:
[0. 0. 0. 0.]
(4,)


In [3]:
# 2-2번

# sigmoid 
def sigmoid(x):
    return 1/(1+np.exp(-x))

# 추정값 y_hat
y_hat = sigmoid(w.dot(x.T))
print("처음 추정값: ",y_hat)
print()

# 초기 평균 에러
first_error = (1/9) * (y-y_hat).dot((y-y_hat).T)
print("초기 에러 : ",first_error)
print()

# 잔차
print(y-y_hat)
print()

# 1회 시행의 w update
w_update = w + (0.1 / 9) * (y-y_hat).dot(x)
print("업데이트 된 w : ",w_update)
print()

# 업데이트된 y_hat
y_hat_update = sigmoid(w_update.dot(x.T))
print("업데이트 된 추정값 : ",)
print(y_hat_update)
print()

# 업데이트된 평균에러
error_update = (1/9) * (y-y_hat_update).dot((y-y_hat_update).T)
print("업데이트 후 error : ",error_update)

처음 추정값:  [0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]

초기 에러 :  0.25

[ 0.5 -0.5  0.5  0.5 -0.5 -0.5  0.5 -0.5  0.5]

업데이트 된 w :  [ 0.00555556  0.          0.01097222 -0.12166667]

업데이트 된 추정값 : 
[0.48061354 0.05144412 0.47756837 0.47344826 0.4880167  0.48079244
 0.48992706 0.49004645 0.481665  ]

업데이트 후 eror :  0.22899034658412315


In [4]:
# 2-3번

kim_data = np.array([1,1,0.1,0.5])
p = sigmoid(w_update.dot(kim_data.T))
print(p)
print()
if p >= 0.5:
    print("kim vote : +")
else:
    print("kim vote : -")

0.4864581736551051

kim vote : -
