In [160]:
import numpy as np
import numpy as pd

def sigmoid(x):
    return 1/(1+np.exp(-x))


x = np.array([[1,0.85,0.76,1],
              [1,0,0.24,1],
              [0,0.625,0.84,1],
              [0,0.45,0.96,1],
              [1,0.225,0.46,1],
              [0,0.25,0.7,1],
              [1,0.7,0.44,1],
              [0,0.3,0.4,1],
              [0,0.125,0.66,1]])

y = np.array([[1,0],
             [0,1],
             [1,0],
             [1,0],
             [0,1],
             [0,1],
             [1,0],
             [0,1],
             [1,0]])

# x1 = sex , x2 = age, x3 = income, x4 = bias
x= x.T
print(x.shape)
x_weight = np.zeros([2,4])
print(x_weight)
print("input layer x :")
print(x)
h_weight = np.array([[0.1,0.1,0.1],
                     [0.1,0.1,0.1]])



# hidden layer
z_x = x_weight.dot(x)
print(z_x)
print("hidden layer h : ")
h = sigmoid(z_x)
h = np.vstack((h,np.ones([1,9])))
print(h)
print(h.shape)


# output layer
z_h = h_weight.dot(h)
print(z_h)
o = sigmoid(z_h)
print(o)
print(z_h.shape,o.shape)

(4, 9)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
input layer x :
[[1.    1.    0.    0.    1.    0.    1.    0.    0.   ]
 [0.85  0.    0.625 0.45  0.225 0.25  0.7   0.3   0.125]
 [0.76  0.24  0.84  0.96  0.46  0.7   0.44  0.4   0.66 ]
 [1.    1.    1.    1.    1.    1.    1.    1.    1.   ]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
hidden layer h : 
[[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
 [1.  1.  1.  1.  1.  1.  1.  1.  1. ]]
(3, 9)
[[0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2]]
[[0.549834 0.549834 0.549834 0.549834 0.549834 0.549834 0.549834 0.549834
  0.549834]
 [0.549834 0.549834 0.549834 0.549834 0.549834 0.549834 0.549834 0.549834
  0.549834]]
(2, 9) (2, 9)


In [161]:
print(y.T.shape)
print(o.shape)

print((y.T-o).shape,o.T.shape,(1-o).shape)
h_delta = (y.T-o).dot(o.T).dot(1-o)
print(h_delta.T)
print(h_weight)
print(h_delta.T.shape,h_weight.shape,h.T.shape,(1-h).shape)
print(h_delta.T.dot(h_weight))


(2, 9)
(2, 9)
(2, 9) (9, 2) (2, 9)
[[ 0.02549125 -0.4695419 ]
 [ 0.02549125 -0.4695419 ]
 [ 0.02549125 -0.4695419 ]
 [ 0.02549125 -0.4695419 ]
 [ 0.02549125 -0.4695419 ]
 [ 0.02549125 -0.4695419 ]
 [ 0.02549125 -0.4695419 ]
 [ 0.02549125 -0.4695419 ]
 [ 0.02549125 -0.4695419 ]]
[[0.1 0.1 0.1]
 [0.1 0.1 0.1]]
(9, 2) (2, 3) (9, 3) (3, 9)
[[-0.04440506 -0.04440506 -0.04440506]
 [-0.04440506 -0.04440506 -0.04440506]
 [-0.04440506 -0.04440506 -0.04440506]
 [-0.04440506 -0.04440506 -0.04440506]
 [-0.04440506 -0.04440506 -0.04440506]
 [-0.04440506 -0.04440506 -0.04440506]
 [-0.04440506 -0.04440506 -0.04440506]
 [-0.04440506 -0.04440506 -0.04440506]
 [-0.04440506 -0.04440506 -0.04440506]]


In [282]:
print((y.T[0]-o[0]).shape,o.shape,h.shape)
print((y.T[0]-o[0]).dot(o.T).dot(1-o).dot(h.T))
h[:2]

(9,) (2, 9) (3, 9)
[0.11471062 0.11471062 0.22942124]


array([[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]])

In [287]:
# h_delta
h_delta = (y.T-o).dot(o.T).dot(1-o)
h_delta

array([[ 0.02549125,  0.02549125,  0.02549125,  0.02549125,  0.02549125,
         0.02549125,  0.02549125,  0.02549125,  0.02549125],
       [-0.4695419 , -0.4695419 , -0.4695419 , -0.4695419 , -0.4695419 ,
        -0.4695419 , -0.4695419 , -0.4695419 , -0.4695419 ]])

In [438]:
temps =(y.T-o).dot(o.T).dot(1-o).T.dot(h_weight[:,:2])


In [439]:
x_delta = temps.T.dot(h[:2].T).dot((1-h[:2]))
x_delta 

array([[-0.19982279, -0.19982279, -0.19982279, -0.19982279, -0.19982279,
        -0.19982279, -0.19982279, -0.19982279, -0.19982279],
       [-0.19982279, -0.19982279, -0.19982279, -0.19982279, -0.19982279,
        -0.19982279, -0.19982279, -0.19982279, -0.19982279]])

In [441]:
h_delta.dot(h.T)

array([[ 0.11471062,  0.11471062,  0.22942124],
       [-2.11293853, -2.11293853, -4.22587707]])

In [416]:
h_weight_update = h_weight + h_delta.dot(h.T)
h_weight_update

array([[ 0.21471062,  0.21471062,  0.32942124],
       [-2.01293853, -2.01293853, -4.12587707]])

In [419]:
x_weight_update = x_weight + x_delta.dot(x.T)
x_weight_update, x_delta.dot(x.T)

(array([[-0.79929117, -0.70437534, -1.09103244, -1.79840512],
        [-0.79929117, -0.70437534, -1.09103244, -1.79840512]]),
 array([[-0.79929117, -0.70437534, -1.09103244, -1.79840512],
        [-0.79929117, -0.70437534, -1.09103244, -1.79840512]]))