In [1]:
import numpy as np

def sigmoid(x):
    return 1/(1+np.exp(-x))


x = np.array([[1,0.85,0.76,1],
              [1,0,0.24,1],
              [0,0.625,0.84,1],
              [0,0.45,0.96,1],
              [1,0.225,0.46,1],
              [0,0.25,0.7,1],
              [1,0.7,0.44,1],
              [0,0.3,0.4,1],
              [0,0.125,0.66,1]])

y = np.array([[1,0],
             [0,1],
             [1,0],
             [1,0],
             [0,1],
             [0,1],
             [1,0],
             [0,1],
             [1,0]])

# x1 = sex , x2 = age, x3 = income, x4 = bias
x= x.T
print(x.shape)
x_weight = np.zeros([2,4])
print(x_weight)
print("input layer x :")
print(x)
h_weight = np.array([[0.1,0.1,0.1],
                     [0.1,0.1,0.1]])



# hidden layer
z_x = x_weight.dot(x)
print(z_x)
print("hidden layer h : ")
h = sigmoid(z_x)
h = np.vstack((h,np.ones([1,9])))
print(h)
print(h.shape)


# output layer
z_h = h_weight.dot(h)
print(z_h)
o = sigmoid(z_h)
print("output layer: ")
print(o)
print(z_h.shape,o.shape)
print(o.T)

(4, 9)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
input layer x :
[[1.    1.    0.    0.    1.    0.    1.    0.    0.   ]
 [0.85  0.    0.625 0.45  0.225 0.25  0.7   0.3   0.125]
 [0.76  0.24  0.84  0.96  0.46  0.7   0.44  0.4   0.66 ]
 [1.    1.    1.    1.    1.    1.    1.    1.    1.   ]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
hidden layer h : 
[[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
 [1.  1.  1.  1.  1.  1.  1.  1.  1. ]]
(3, 9)
[[0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2]]
output layer: 
[[0.549834 0.549834 0.549834 0.549834 0.549834 0.549834 0.549834 0.549834
  0.549834]
 [0.549834 0.549834 0.549834 0.549834 0.549834 0.549834 0.549834 0.549834
  0.549834]]
(2, 9) (2, 9)
[[0.549834 0.549834]
 [0.549834 0.549834]
 [0.549834 0.549834]
 [0.549834 0.549834]
 [0.549834 0.549834]
 [0.549834 0.549834]
 [0.549834 0.549834]
 [0.549834 0.549834]
 [0.549834 0.549834]]


In [2]:
print("h_delta: ")
h_delta = -(y.T-o)*(o)*(1-o)
print(h_delta.T)
print()

print()

h_delta: 
[[-0.11142355  0.13609303]
 [ 0.13609303 -0.11142355]
 [-0.11142355  0.13609303]
 [-0.11142355  0.13609303]
 [ 0.13609303 -0.11142355]
 [ 0.13609303 -0.11142355]
 [-0.11142355  0.13609303]
 [ 0.13609303 -0.11142355]
 [-0.11142355  0.13609303]]




In [3]:
y.shape

(9, 2)

In [4]:
o.shape

(2, 9)

In [5]:
x_delta=(y.T-o)*o*(1-o)
x_delta.T

array([[ 0.11142355, -0.13609303],
       [-0.13609303,  0.11142355],
       [ 0.11142355, -0.13609303],
       [ 0.11142355, -0.13609303],
       [-0.13609303,  0.11142355],
       [-0.13609303,  0.11142355],
       [ 0.11142355, -0.13609303],
       [-0.13609303,  0.11142355],
       [ 0.11142355, -0.13609303]])

In [6]:
h_weight[:,:2]

array([[0.1, 0.1],
       [0.1, 0.1]])

In [7]:
h[0:2].T

array([[0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5]])

In [8]:
x_delta.T.dot(h_weight[:,:2])*h[0:2].T*(1-h[0:2].T)

array([[-0.00061674, -0.00061674],
       [-0.00061674, -0.00061674],
       [-0.00061674, -0.00061674],
       [-0.00061674, -0.00061674],
       [-0.00061674, -0.00061674],
       [-0.00061674, -0.00061674],
       [-0.00061674, -0.00061674],
       [-0.00061674, -0.00061674],
       [-0.00061674, -0.00061674]])

In [9]:
o = sigmoid(0.2)
-(1-o)*o*(1-o)

-0.1114235461366134

In [10]:
# w1_h1
-(1-0.5498)*0.5498*(1-0.5498) *0.5

-0.05571674299600001

In [11]:
((1-o)*o*(1-o)*0.1+(0-o)*o*(1-o)*0.1)*0.5*0.5*1

-0.000616737010965829

In [12]:
h_weight

array([[0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1]])

In [13]:
h_delta.T*h.T[:,:2]

array([[-0.05571177,  0.06804651],
       [ 0.06804651, -0.05571177],
       [-0.05571177,  0.06804651],
       [-0.05571177,  0.06804651],
       [ 0.06804651, -0.05571177],
       [ 0.06804651, -0.05571177],
       [-0.05571177,  0.06804651],
       [ 0.06804651, -0.05571177],
       [-0.05571177,  0.06804651]])